### ISSUE TITLE
about the Makefile

### ISSUE THREAD

**Issue by xpsair** [bitly/dablooms#68]
Dablooms is very benefit for understanding the bloom filter. The Makefile of dablooms is very good and professional, but it is a little bit too professional for beginners :)

I believe that dablooms prefer to let people concentrate on the bloom filter itself rather than how to read and spend time on understanding the Makefile. 

I wish their would be a very simple version of the Makefile.

**Comment by xpsair** [comment]
```c
g++ source_file.c head_file.h -o your_target -fPIC -g -Wall -O2 -lm
```
this cmd seems works :)

**Comment by ploxiln** [comment]
Your command can work, but you must list all the `.c` files, and not the `.h` files. Also, this is plain c, so you can use just "gcc" instead of "g++". Actually "cc" is the "default c compiler" on most unixes including Mac OS X and Linux. And if you don't want to just copy the .c and .h files into your own project, but install dablooms as a library, then you need to understand a bit more about linking to it.

However, beginners don't really need to understand the contents of the Makefile, particularly due to the `make help` output.

The complexity is, in my opinion, mostly in the part that attempts to support dynamic shared libraries in both Mac OS X and Linux. I don't want to take that out and only support one of them. If you have a specific way to simplify the Makefile without breaking a common use case, I'd be happy to see a pull request :)
